site_name: grAIder Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

nav:
  - Home: index.md
  - Learning Science: learning_science.md
  - Students Manual: students.md
  - Teachers Manual: teachers.md
  - Current Implementation: current_implementation.md
  - Feature Requests: feature_requests.md
